// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSIzPgkkwmp8vOLqhl8GCVTZphvtRx6TI',
    appId: '1:629757564413:web:52ed57d71891335c00f594',
    messagingSenderId: '629757564413',
    projectId: 'vagabondflutter-app',
    authDomain: 'vagabondflutter-app.firebaseapp.com',
    storageBucket: 'vagabondflutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8oFBkCZiE0_0m45Rb3d24NrFHH9SQzE4',
    appId: '1:629757564413:android:b5593223e86c8cd700f594',
    messagingSenderId: '629757564413',
    projectId: 'vagabondflutter-app',
    storageBucket: 'vagabondflutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoGNGmQRvfTNtvXq3F9k4ygR5ic5ouWfQ',
    appId: '1:629757564413:ios:0be0145123c18d7500f594',
    messagingSenderId: '629757564413',
    projectId: 'vagabondflutter-app',
    storageBucket: 'vagabondflutter-app.appspot.com',
    iosBundleId: 'com.example.vagabondapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoGNGmQRvfTNtvXq3F9k4ygR5ic5ouWfQ',
    appId: '1:629757564413:ios:0be0145123c18d7500f594',
    messagingSenderId: '629757564413',
    projectId: 'vagabondflutter-app',
    storageBucket: 'vagabondflutter-app.appspot.com',
    iosBundleId: 'com.example.vagabondapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSIzPgkkwmp8vOLqhl8GCVTZphvtRx6TI',
    appId: '1:629757564413:web:08708c9a1a53918800f594',
    messagingSenderId: '629757564413',
    projectId: 'vagabondflutter-app',
    authDomain: 'vagabondflutter-app.firebaseapp.com',
    storageBucket: 'vagabondflutter-app.appspot.com',
  );
}
